name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy rustfmt

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config clang libpipewire-0.3-dev

      - name: Linting
        run: |
          cargo clippy --workspace --all-features -- -D warnings
          cargo fmt --all -- --check

      - name: Debug builds
        run: cargo build
