name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            output: pwmenu-x86_64-linux-gnu
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            output: pwmenu-aarch64-linux-gnu

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config clang libpipewire-0.3-dev

      - name: Build binary
        run: |
          cargo build --release
          cp target/release/pwmenu ${{ matrix.output }}
          strip ${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*/pwmenu-*"
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, '-') }}
